### ISSUE TITLE
Apply subdirectories?

### ISSUE THREAD

**Issue by noqcks** [tazjin/kontemplate#111]
Does Kontemplate have some type of recursive flag like kubectl? `-R` ?

**Comment by tazjin** [comment]
If you use have a parent resource set then including that will include all of its specified children, too. Is that what you're looking for?

**Comment by noqcks** [comment]
Yeah, essentially.

Right now the templating is only 1 level deep yaml files afaik

**Comment by merlineus** [comment]
Hello,

I also have a question about subdirs. Can I place templates on the third level subfolder:

```
include:
  - name: cluster
    include:
      - name: deployments
        include:
          - name: dashboard
```

I receive error "kontemplate: error: Error templating resource sets: No valid resource sets included!" when trying to apply such template "-i cluster/deployments/dashboard"
