### ISSUE TITLE
Interpolating yaml as a template variables

### ISSUE THREAD

**Issue by jsierles** [tazjin/kontemplate#126]
I have a lot of secrets being used as environment vars. I'd like to share this config across deployments. For example:

```
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: "database-url"
              key: "database-url"
```

Is there a way to do this, as opposed to interpolating a single value, with kontemplate?
