### ISSUE TITLE
Templating for global variables

### ISSUE THREAD

**Issue by phillipj** [tazjin/kontemplate#140]
Have you considered allowing global variables to support the same templating features as resource sets has?

My scenario would be something like this:

```yaml
---
context: k8s.cluster.com
global:
  version: {{ gitHEAD }}
include:
  - name: my-awesome-app

  ...
```

Mainly for convenience sake; making the default behaviour to use whatever is currently at `HEAD`, but still allow `--var version=an-explicit-sha` to be provided if needed.

**Comment by phillipj** [comment]
FYI this is what I'm getting when trying this in v1.6.0:

```
$ kontemplate template my-cluster.yaml
kontemplate: error: Error loading context: Context loading failed on file my-cluster.yaml due to:
error converting YAML to JSON: yaml: invalid map key: map[interface {}]interface {}{"gitHEAD":interface {}(nil)}
```

Another approach could to be to inline this in the resource sets, example psudeoish config;

```yaml
spec:
  containers:
    - image: xyz.ecr.eu-central-1.amazonaws.com/my-awesome-app:{{ getOrElse .version gitHEAD }}
      name: my-awesome-app
```
