### ISSUE TITLE
kontemplate create does not send everything to kubectl

### ISSUE THREAD

**Issue by runar-rkmedia** [tazjin/kontemplate#150]
if Service, Deployment etc. are in the same file, `kontemplate create vars.yml` will not send all of them to `kubectl`. 

Currently, in our project, we have about 10 groups of services and deployments. All of them have the Service at the top of the file, so `kubectl` recieves all of these. Strangely, it recieves only a single Deployment, even though the syntax for them are the same.

The current workaround for us was to output the files to a directory first, and the use `kubectl create ` on that.

```bash
kontemplate template vars.yml -o myDir
kubectl create -f myDir
````

## Example from `mysql.yml` where Deployment is not sent to `kubectl`
```yml
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: '{{ .mySqlRootPassword }}'
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
```
