### ISSUE TITLE
Override nested variables

### ISSUE THREAD

**Issue by runar-indico** [tazjin/kontemplate#163]
In our current workflow, we define a set of global variables and then override these in per-deployment-var-files. We would love the ability to be able to override single values in a globally defined map, without redefining the whole map.

For instance:

globals.yml
```
foo:
  bar:
    one: 1
    two: 2
  baz:
    three: 3
    four: 4
```

then in server1-vars.yml
```
foo.baz.three: 42
```

then in server2-vars.yml
```
foo.baz.three: 101
```

Both of these last configs would like to override the value `foo.baz.three`, but without declaring all the other values. Is this possible?
