### ISSUE TITLE
Ability to resuse the template vairable within the master template and k8s resources

### ISSUE THREAD

**Issue by var23rav** [tazjin/kontemplate#167]
Like i explained below, the configuration and usage of template varaiable are just representaion.

1. Is it possible to reuse the template variable in kontemplate yaml file 
2. And also is it possible to dynamically get the template varibale name  and use it value in k8s resouse yaml file 
----

1.  Kontepmate yaml file
```
context: **
global:
  namespace: test
include:
- name: base
  path: base.yaml

# setup for bob
- name: back-end-for-bob
   path: back-end
   values:
      env: bob
      port: 7070
- name: front-end-for-bob
   path: front-end
  values:
     env: bob
     port: 7080
     # Is there any way to get the value from "back-end-for-bob.port" instead of hard coding ?
     api_port: "7070" 
     # Is possible to reuse a global variable(bob's test shop) here itselt ?
     app_name: "{{ .env }}'s {{ .namespace}} shop"  

# setup for jhon
- name: back-end-for-jhon
   path: back-end
   values:
      env: jhon
      port: 7071
- name: front-end-for-jhon
   path: front-end
  values:
      env: jhon
      port: 7081
      #  Is there any way to get the value from "back-end-for-jhon.port" instead of hard coding ?
      api_url: "7071" 
      # Is possible to reuse a global variable(jhon's test shop) here itselt ?
      app_name: "{{ .env }}'s {{ .namespace}} shop"  
```
----
2. Now try to dynamically genrate a template variable in k8s resouce yaml and use its name
Here I need to dynamically choose the back-end service name inside front-end deployment file, but note that i have two type of back-end conf one for bob another for jhone(env).
Is there any way to achive this.
front-end/front-end-deployment.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end-{{ .env}}
  namespace: {{ .namespace }}
.
.
.
spec:
      containers:
      - name: front-end
        image: my_front_end_image
        imagePullPolicy: Never
        env:
        - name: api_url
          # 
          value: "service-back-end-{{ .env}}.{{ .namespace }}:{{  .back-end-for-[.env].port }}"
```
