### ISSUE TITLE
Support inserting change-cause annotation

### ISSUE THREAD

**Issue by tazjin** [tazjin/kontemplate#63]
A `Deployment` can have a `kubernetes.io/change-cause` annotation that will show up in `kubectl rollout history`.

Kontemplate should support some sort of easy way to insert this sanely, e.g.:

```
kind: Deployment
metadata:
  annotations:
    {{ .kontemplateChangeCause }}
```

to expand (intelligently) to something like

```
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: kontemplate-v1.1 w/ rev-${gitHashOfConfigRepo}
```

(just making up a format here but you get the gist of it)
