### ISSUE TITLE
Add support for importing variables from other files

### ISSUE THREAD

**Issue by Globegitter** [tazjin/kontemplate#64]
I really like the idea and simplicity of this project but one thing that seems to be missing in my opitinon is to be able to set variable hierarchical (for sharing between environments). So I might have a `cluster.yaml` file which has:

```yaml
---
global:
  globalVar: lizards
include:
  - name: some-api
    values:
      version: 1.0-0e6884d
      importantFeature: true
      apiPort: 4567
```

and then `prod-cluster.yaml` somehow inherits from the base file. So it gets all defined variable from `cluster.yaml` and can override them if wanted, e.g.:
```yaml
---
include:
  - name: some-api
    values:
      importantFeature: false
      someOtherVar: something
```

This will take the `version, globalVar and apiPort` from `cluster.yaml`, override `importantFeature` and add `someOtherVar`.

Though the open question is on how to achieve that the best way. Maybe through some import feature? Or placing the files in a hierarchical way on the file system?

So e.g.
```
.
├── cluster.yaml
└── dev
    ├── cluster.yaml
└── staging
    ├── cluster.yaml
└── prod
    ├── cluster.yaml
└── some-api
    ├── deployment.yaml
    └── service.yaml
```

Those are just some ideas on how to implement it. What do you think?

**Comment by tazjin** [comment]
Hey! Glad to hear you like the project :-)

I'd prefer to avoid building too many hierarchies of things, but I was considering some sort of flat variable import feature:

```
# Some resource set "my-service" uses a "servicePort" variable
# my-service/service.yaml
  [... imagine some things ...]
  port: {{ .servicePort }}

# cluster.yaml:
---
include:
  - name: my-service

# my-shared-variables.yaml:
servicePort: 4567
```

You could then do something like:

`kontemplate template cluster.yaml --extra-vars my-shared-variables.yaml`

(need a better flag name)

The one hierarchical question that I can't escape with this is what the override order is. Lets assume `servicePort` is specified in all of: 

* `my-service/default.json`
* `cluster.yaml/global`
* `cluster.yaml/specific`
* `my-shared-variables.yaml`

Which one should apply at the end? Currently the hierarchy is

`[cluster.yaml/specific] > [cluster.yaml/global] > [resource set default]`

and the extra vars should come in either before or after global, but I'm not sure.

**Comment by Globegitter** [comment]
I can understand if you want to stay away from hierarchy of things and keep things flat. Now just thinking about it, therer are two other ideas I have, either we could have true default values, so:

```
# Some resource set "my-service" uses a "servicePort" variable
# my-service/service.yaml
  [... imagine some things ...]
  port: {{ .servicePort:80 }}
```

or similar and if servicePort is not set then it defaults to 80. What I like about this, it keeps things very simple but on the ohter hand you might want to have a shared variable that you use in different resources and here you would have to set that as a default everywhere.

The other idea, how about doing a simple import in the file itself, e.g given my example in the initial post, we have `prod-cluster.yaml`:
```
----
import: cluster.yaml
include:
  - name: some-api
    values:
      importantFeature: false
      someOtherVar: something
```

About the hierarchy, maybe it makes sense to be able to define variables as global or specific in the shared variables, and then it could be:

`[cluster.yaml/specific] > [shared.yaml/specific] > [cluster.yaml/global] >  [shared.yaml/global] > [resource set default]`

or otherwise I would probably do:

`[cluster.yaml/specific] > [cluster.yaml/global] >  [shared.yaml] > [resource set default]`

Also you are mentioning here `resource set default`. Can you already set default values for resources?

**Comment by tazjin** [comment]
Default variables are currently supported by dropping in a `default.yaml` or `default.json` into your resource set folder, so for example:

```
# my-api/api.yaml
kind: Deployment
template:
  spec:
    containers:
      - image: 'my-api:{{ .version }}'

# my-api/default.json
{
  "version": "1.0-SNAPSHOT"
}
```

(You can also use a `default.yaml` instead of JSON, but I usually use JSON due to it being easier to machine-update in the [CI flow](https://github.com/tazjin/kontemplate/issues/28) that we have).

-----------

> The other idea, how about doing a simple import in the file itself

Good point, I think this may be better than having it as a CLI-flag because it's declarative. I'll mock this up as a test!
