### ISSUE TITLE
Add --include-file / --exclude-file for specific files in resource sets

### ISSUE THREAD

**Issue by samiralajmovic** [tazjin/kontemplate#69]
This is allowed with regular kubectl:

```sh
$ kubectl apply -f path/to/file-deploy.yaml
```

These don't seem to work:
```sh
$ kontemplate template beta-cluster.yaml -i path/to/file-deploy.yaml
 │Loading resources for path/to/file-deploy.yaml 

$ kontemplate template beta-cluster.yaml -i path/to/file-deploy
 │Loading resources for path/to/file-deploy
```
Meaning, they don't output the rendered file.

I attempted with the following `beta-cluster.yaml`:

```yaml
---
context: lala
include:
  - name: path/to
    values:
      lala: land

  - name: path/to/file-deploy
    values:
      configStuff: stuff

  - name: path/to/file-deploy.yaml
    values:
      configStuff: stuff
```

**Comment by tazjin** [comment]
Currently include/exclude works on resource sets (i.e. the whole folder containing resources and potentially default values).

I could theoretically extend that to allow targeting specific files but there are a few considerations (do default vars still get loaded from the files basedir?) that I need to think about.

**Comment by samiralajmovic** [comment]
Well I would assume no since that's what globals are for?

```yaml
  - name: some-api/hello
    values:
      version: 1.0-0e6884d
      importantFeature: true
      apiPort: 4567
```
`some-api/lala` would not inherit variables from `some-api/hello`. I do think this feature is needed since kubectl allows it. I also think kubectl apply / replace is idempotent when you write over with the same config unless you do add the --force label, then it deletes and adds the new resource.
