### ISSUE TITLE
Decouple resource set name and path

### ISSUE THREAD

**Issue by tazjin** [tazjin/kontemplate#70]
Currently the path from which a resource set's files are loaded is inferred from the name of the resource set.

In some situations, such as importing the same resource set multiple times with different configuration, the user may want to split paths and names. This should be supported:

```
- name: api-europe
  path: some-api
  values:
    location: europe
- name: api-asia
  path: some-api
  values:
    location: asia
```

thus making it possible to use `--include / --exclude api-asia` for example.
