### ISSUE TITLE
path directive doesn't seem to work in yml files

### ISSUE THREAD

**Issue by adimarco** [tazjin/kontemplate#88]
I recreated the example from the docs with `forwarder-asia` etc. after I noticed `path` not seeming to work, and even that example doesn't seem to work (unless I'm missing something)

I've got my `forwarders.yml` copy/pasted from the example, i.e.:

```
include:
  - name: forwarder-europe
    path: tools/forwarder
    values:
      source: europe
  - name: forwarder-asia
    path: tools/forwarder
    values:
      source: asia
```

My directory structure is:
<pre>
test
├── forwarders.yml
└── tools
    └── forwarder
        └── forwarder.yml
</pre>

And just to prove the variable substitution works, my `tools/forwarder/forwarder.yml` is just:
```
source: {{ .source }}
```

But, I (sliently) get no output when I run things through `kontemplate template` like so:
```
$ kontemplate template test/forwarders.yml 
Loading resources for forwarder-europe
Loading resources for forwarder-asia
```

If I change that top-level `forwarders.yml` from the example to remove the `path` directive and just use the same `name` for both like so:
```
include:
  - name: tools/forwarder
    values:
      source: europe
  - name: tools/forwarder
    values:
      source: asia
```

I get the output I would originally have expected from the example:
```
$ kontemplate template test/forwarders.yml 
Loading resources for tools/forwarder
Loading resources for tools/forwarder
Rendered file tools/forwarder/forwarder.yml:
source: europe
Rendered file tools/forwarder/forwarder.yml:
source: asia
```

I've tried several different configurations with this, and they all seem to point back to the `path` directive just being ignored.
