### ISSUE TITLE
Support resource collections

### ISSUE THREAD

**Issue by tazjin** [tazjin/kontemplate#9]
For slightly better organisational structure. Assuming for example:

```
.
├── controllers
│   ├── flink-controller
│   └── letsencrypt-controller
├── test-cluster.yaml
```

It should be possible to write in `test-cluster.yaml`:

```yaml
include:
  - name: controllers
     including:
      - name: flink-controller
      - name: letsencrypt-controller
```

(syntax TBD)
